<?php
echo $this->doctype();
?>

<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('POC - Playground CMS')->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <!-- Le styles -->
        <link href="/zfcadmin/css/base.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" />

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); ?>
    </head>
    
    <body class="background-dark">   
        <div class="single-widget-container error-page">
            <section class="widget transparent widget-404">
                <div class="body">
                    <div class="row">
                        <div class="col-md-5">
                            <h1 class="text-align-center">404</h1>
                        </div>
                        <div class="col-md-7">
                            <div class="description">
                                <h3>Opps, it seems that this page does not exist here.</h3>
                                <p>If you are sure it should, search for it.</p>
                                <p> Message : <?php echo $this->message ?> </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="widget widget-404-search">
                <div class="body no-margin">
                    <form class="form-inline form-search no-margin text-align-center" method="get" action="#"
                          role="form">
                        <div class="input-group">
                            <input type="search" class="form-control"
                                   placeholder="Article, Page, Tag">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit">
                                    &nbsp; Search &nbsp;
                                </button>
                            </span>
                        </div>
                    </form>
                </div>
            </section>
        </div>



        <!-- Scripts -->
        <script type="text/javascript" src="/zfcadmin/js/script_playground.js"></script>
        <?php
            echo $this->headScript();
            echo $this->inlineScript();
        ?>
    </body> 
</html>