     <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">PGCMS</a>
        </div>
        <?php $this->getBlock('block-html-form'); ?>
        <!--/.navbar-collapse -->
      </div>
    </div>
    
    <div class="jumbotron">
      <div class="container">
        <h1><?php $this->getBlock('block-html-hello-world'); ?></h1>
        <?php $this->getBlock('block-html-content-1'); ?>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-3">
          <h2><?php $this->getBlock('block-html-hello-world'); ?></h2>
          <?php $this->getBlock('block-html-content-2'); ?>
        </div>
        <div class="col-md-3">
          <h2><?php $this->getBlock('block-html-hello-world'); ?></h2>
          <?php $this->getBlock('block-html-content-2'); ?>
       </div>
        <div class="col-md-3">
          <h2><?php $this->getBlock('block-html-hello-world'); ?></h2>
          <?php $this->getBlock('block-html-content-2'); ?>
        </div>
        <div class="col-md-3">
          <?php $this->getBlock('block-list-block'); ?>
        </div>
      </div>

      <hr />
    </div>