<?php
echo $this->doctype();
?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('POC - Playground CMS')->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <!-- Les styles -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); ?>
    </head>
    <body>    


      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('frontend'); ?>">PGCMS</a>
          </div>
          <?php $this->getBlock('block-html-form'); ?>
          <!--/.navbar-collapse -->
        </div>
      </div>
      
      <div class="jumbotron">
        <div class="container">
          <h1><?php $this->getBlock('block-html-hello-world'); ?></h1>
          <?php $this->getBlock('block-html-content-1'); ?>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2><?php $this->getBlock('block-html-hello-world'); ?></h2>
            <?php $this->getBlock('block-html-content-2'); ?>
          </div>
          <div class="col-md-4">
            <h2><?php $this->getBlock('block-html-hello-world'); ?></h2>
            <?php $this->getBlock('block-html-content-2'); ?>
         </div>
          <div class="col-md-4">
            <h2><?php $this->getBlock('block-html-hello-world'); ?></h2>
            <?php $this->getBlock('block-html-content-2'); ?>
          </div>
          <div class="clearfix">&nbsp;</div>
          <div class="col-md-4">
            <?php $this->getBlock('block-list-block'); ?>
          </div>
          <div class="col-md-4">
            <?php $this->getBlock('block-list-block-filters'); ?>
          </div>
          <div class="col-md-4">
            <?php $this->getBlock('block-list-block-sort'); ?>
          </div>
           <div class="clearfix">&nbsp;</div>
          <div class="col-md-12">
            <?php $this->getBlock('block-list-block-filters-sorts-pagers'); ?>
          </div>
        </div>
        <hr />
      </div>

      
    <!-- Les Scripts -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <?php
            echo $this->headScript();
            echo $this->inlineScript();
        ?>
    </body> 
</html>