<?php
echo $this->doctype();
$translation = $this->entity->getTranslations();
?>

<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($translation["titleMeta"])->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta name="description" content="<?php echo $translation["descriptionMeta"] ?>"/>
        <meta name="keywords" content="<?php echo $translation["keywordMeta"] ?>"/>
        
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); ?>
    </head>
    <body>    

        <?php $this->getZone('page_header'); ?>
        <div class="jumbotron">
            <div class="container">
                <?php $this->getZone('page_jumbotron'); ?>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <?php $this->getZone('page_container'); ?>
            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <?php
            echo $this->headScript();
            echo $this->inlineScript();
        ?>
    </body> 
</html>