<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('admin'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active">Search : <?php echo $this->search ?> </li>
            </ol>
        </section>
    </div>
</div>

<section class="widget">
    <header>
        <h4>
            <i class="fa fa-search"></i>
            Result of the search : <?php echo $this->search ?>  (<?php echo count(array('0'));?>)
        </h4>
    </header>
    <div class="clearfix">&nbsp;</div>
    <div class="body">
        <div class="" style="position: relative; overflow: hidden; width: auto; height: auto;"><div id="feed" class="feed" style="overflow: hidden; width: auto; height: auto;">
            <div class="wrapper">
                <div class="vertical-line"></div>
                <section class="widget widget-tabs large">
                    <header>
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#blocks" data-toggle="tab">Blocks (0)</a>
                            </li>
                            <li class="">
                                <a href="#layouts" data-toggle="tab">Layouts (0)</a>
                            </li>
                            <li class="">
                                <a href="#menus" data-toggle="tab">Menus (0)</a>
                            </li>
                            <li class="">
                                <a href="#pages" data-toggle="tab">Pages (0)</a>
                            </li>
                            <li class="">
                                <a href="#templates" data-toggle="tab">Templates (0)</a>
                            </li>
                            <li class="">
                                <a href="#zones" data-toggle="tab">Zones (0)</a>
                            </li>
                            <li class="">
                                <a href="#articles" data-toggle="tab">Articles (0)</a>
                            </li>
                            <li class="">
                                <a href="#categories" data-toggle="tab">Categories (0)</a>
                            </li>
                            <li class="">
                                <a href="#polls" data-toggle="tab">Polls (0)</a>
                            </li>
                            <li class="">
                                <a href="#tags" data-toggle="tab">Tags (0)</a>
                            </li>
                        </ul>
                    </header>
                    <div class="body tab-content">
                        <div id="blocks" class="tab-pane clearfix active">
                            <h5 class="tab-header"><i class="fa fa-code"></i> Blocks</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                        <div id="layouts" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-windows"></i> Layouts</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                        <div id="menus" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-tree"></i> Menus</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                        <div id="pages" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-desktop"></i> Pages</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                        <div id="templates" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-align-justify"></i> Templates</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                        <div id="zones" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-th-large"></i> Zones</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                        <div id="articles" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-edit"></i> Articles</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                        <div id="categories" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-book"></i> Categories</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                        <div id="polls" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-question"></i> Polls</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                        <div id="tags" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-tag"></i> Tags</h5>
                                <ul class="news-list">
                                    <li>
                                    </li>
                                </ul>
                        </div>
                    </div>
                </section>
                

            </div>
        </div>
    </div>
    <div class="clearfix">&nbsp;</div>
</section>