<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 4.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title></title>
</head>
<body>
<table width="100%" cellpadding="0" cellspacing="5" border="0" bgcolor="#F3F3F3">
    <tr>
        <td align="center">
            <table width="516" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td height="589" align="left">
                            <table width="516" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
                                <tr height="589">
                                    <td height="589" width="18" style="font-size:0" valign="top">
                                        
                                    </td>
                                    <td height="589" width="480" style="font-size:0">
                                        <table width="480" cellpadding="0" cellspacing="0" border="0">
                                           
                                            <tr height="487">
                                                <td height="487" width="480" style="font-size:0">
                                                    <table width="480" cellpadding="0" cellspacing="0" border="0">
                                                        <td height="487" width="15" style="font-size:0"></td>
                                                        <td height="487" width="450">
                                                            <table width="450" cellpadding="0" cellspacing="0" border="0">
                                                                <tr height="487">
                                                                    <td height="487" width="450">
                                                                        <table width="450" cellpadding="0" cellspacing="0" border="0">
                                                                            <tr height="32">
                                                                                <td height="32" width="450" style="font-size:18px;">
                                                                                    <font face="Arial">Bonjour,</font>
                                                                                </td>
                                                                            </tr>
                                                                            <tr height="96">
                                                                                <td height="96" width="450" style="font-size:14px;">
                                                                                    <font face="Arial" color="#565656">L'administrateur a bien cr&eacute;&eacute; votre compte<br/><br/>Vous pourrez vous connecter &agrave; votre compte en utilisant votre identifiant et un nouveau mot de passe :</font>
                                                                                </td>
                                                                            </tr>
                                                                            <tr height="77">
                                                                                <td height="77" width="450" bgcolor="F3F3F3" style="font-size:14px;" align="center">
                                                                                    <font face="Arial" color="#565656">Votre Identifiant : <b><?php echo $this->email; ?></b><br/></font>
                                                                                </td>
                                                                            </tr>
                                                                             <tr height="77">
                                                                                <td height="77" width="450" bgcolor="F3F3F3" style="font-size:14px;" align="center">
                                                                                    <font face="Arial" color="#565656">Votre nouveau mot de passe : <b><?php echo $this->password; ?></b><br/></font>
                                                                                </td>
                                                                            </tr>
                                                                            <tr height="62">
                                                                                <td height="62" width="450" style="font-size:0">
                                                                                    
                                                                                </td>
                                                                            </tr>
                                                                            <tr height="70">
                                                                                <td height="70" width="450" style="font-size:14px;" align="center">
                                                                                    <font face="Arial" color="#565656"><b>Merci et &agrave; tr&egrave;s vite sur le backoffice C4 Cactus</font>
                                                                                </td>
                                                                            </tr>
                                                                            <tr height="20">
                                                                                <td height="20" width="450" style="font-size:0">
                                                                                   
                                                                                </td>
                                                                            </tr>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                        <td height="487" width="15" style="font-size:0"></td>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                    <td height="589" width="18" style="font-size:0" valign="top">
                                        
                                    </td>   
                                </tr>   
                            </table>
                    </td>                   
                </tr>   
            </table>        
        </td>
    </tr>
</table>
        
</body>
</html>