<?php $this->plugin('translate')->setTranslatorTextDomain('citroen');?>
<?php echo '<h3>'.$this->result->name.'</h3>'; ?>

<form action="/form" method="post" name="add_form_data" id="add_form_data" class="<?php echo $this->result->id; ?>">
	<ul class="nav nav-list">
        <li>
            <label>Radio ID/Name</label>
            <input type="text" name="input_name" class="form-control"  value="name">
        </li>
		<li>
			<label>Replace Label Text</label>
			<input type="text" name="text_label" class="form-control"  value="Radio Label">
		</li>
        <li>
            <fieldset class="choices">
                <p>Radio  Choices</p>
                <ul class="element_choices">
                    <?php for($i=0; $i<$this->result->length; $i++){ ?>
                    <li class="duplicate_input">
                        <input class="input-small" type="text" value="Radio" name="rem<?php echo $i;?>">
                        <button class="btn btn-mini btn-danger form-control" id="rem<?php echo $i;?>">remove</button>
                        <button class="btn btn-mini btn-info form-control" id="def<?php echo $i;?>">set default</button>
                    </li>
                    <?php } ?>
                    <button class="btn btn-mini btn-success form-control" id="add_new_radio_field">add new field</button>
                </ul>
            </fieldset>
        </li>
        <li>
            <label>Radio Input Class</label>
            <input type="text" name="number_class" class="form-control"   placeholder="class1 class2..">
        </li>
        <li>
            <label>Radio Input Id</label>
            <input type="text" name="number_id" class="form-control"  placeholder="custom id">
        </li>
        <li>
            <label>Label Element Class</label>
            <input type="text" name="number_label_class" class="form-control"  placeholder="class1 class2..">
        </li>
        <li>
            <label>Label Element Id</label>
            <input type="text" name="number_label_id" class="form-control"   placeholder="custom id">
        </li>
		<li>
			<br><button class="btn btn-primary" id="add_form_radio">Save</button>
		</li>
	</ul>
</form>

<?php echo '<code>'.$this->result->id.'</code>'; ?>