<?php $article = $this->article; ?>
<?php $translation = $article->getTranslations(); ?>

<?php $categories = $article->getCategories(); ?>
<h6>
    <?php foreach ($categories as $category) : ?>
        <?php $translationCategory = $category->getTranslations(); ?>
        <span class="label label-primary"><?php echo $translationCategory["title"]; ?></span>
    <?php endforeach; ?>
</h6>


<h2><?php echo $translation['title']; ?></h2>
<p><?php echo $article->getUpdatedAt()->format('d/m/Y H:i:s'); ?> by <?php echo $article->getAuthor(); ?></p>
<?php $tags = $article->getTags(); ?>
<p>
    <?php foreach ($tags as $tag) : ?>
        <?php $translationTag = $tag->getTranslations(); ?>
        <span class="badge"><?php echo $translationTag["title"]; ?></span>
    <?php endforeach; ?>
</p>
<?php echo $translation['content']; ?>




