<div class="col-md-12">
    <ul>Category
        <?php foreach ($this->results as $result) : ?>
            <li class="col-md-12">
                <?php $category = $result; ?>
                <?php $category->setTranslatableLocale($this->ressource->getLocale()); ?>
                <?php $this->em->refresh($category); ?>
                <a href="<?php echo $this->getUrl($category)?>"><?php echo $category->getTitle(); ?></a>
            </li>  
        <?php endforeach; ?>
    </ul>
</div>
