<div class="col-md-12">
    <ul> Tags
        <?php foreach ($this->results as $result) : ?>
            <li class="col-md-12">
                <?php $tag = $result; ?>
                <?php $tag->setTranslatableLocale($this->ressource->getLocale()); ?>
                <?php $this->em->refresh($tag); ?>
                <a href="<?php echo $this->getUrl($tag)?>"><?php echo $tag->getTitle(); ?></a>
            </li>  
        <?php endforeach; ?>
    </ul>
</div>
