<div class="col-md-12">
    <?php $poll = $this->poll; ?>
    <?php $poll->setTranslatableLocale($this->ressource->getLocale()); ?>
    <?php $this->em->refresh($poll); ?>
    <h2><?php echo $poll->getQuestion(); ?></h2>
    <hr />
    <?php foreach ($answers as $answer) : ?>
        <?php $answer->setTranslatableLocale($this->ressource->getLocale());?>
        <?php $this->em->refresh($answer); ?>
        <div class="list-group">
            <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading"><?php echo $answer->getAnswer(); ?></h4>
            </a>
        </div>
    <?php endforeach; ?>
</div>
