<?php $this->plugin('translate')->setTranslatorTextDomain('citroen');?>
<?php echo '<h3>'.$this->translate($this->result->name).'</h3>'; ?>

<form action="/form" method="post" name="add_form_data" id="add_form_data" class="<?php echo $this->result->id; ?>">
	<ul class="nav nav-list">
        <li>
            <label><?php echo $this->translate('Checkbox ID/Name'); ?></label>
            <input type="text" name="input_name" class="form-control"  value="name">
        </li>
		<li>
			<label><?php echo $this->translate('Replace Label Text'); ?></label>
			<input type="text" name="text_label"class="form-control"  value="Checkboxes Label">
		</li>
        <li>
            <fieldset class="choices">
                <p><?php echo $this->translate('Checkbox Choices'); ?></p>
                <ul class="element_choices">
                    <?php for($i=0; $i<$this->result->length; $i++){ ?>
                    <li class="duplicate_input">
                        <input class="input-small form-control" type="text" value="Checkbox" name="rem<?php echo $i;?>">
                        <button class="btn btn-mini btn-danger form-control" id="rem<?php echo $i;?>"><?php echo $this->translate('remove'); ?></button>
                        <button class="btn btn-mini btn-info form-control" id="def<?php echo $i;?>"><?php echo $this->translate('set default'); ?></button>
                    </li>
                    <?php } ?>
                    <button class="btn btn-mini btn-success form-control" id="add_new_checkbox_field"><?php echo $this->translate('add new field'); ?></button>
                </ul>
            </fieldset>
        </li>
        <li style="display:none;">
            <label><?php echo $this->translate('Checkbox Input Class'); ?></label>
            <input type="text" name="number_class" class="form-control" placeholder="class1 class2..">
        </li>
        <li style="display:none;">
            <label><?php echo $this->translate('Checkbox Input Id'); ?></label>
            <input type="text" name="number_id" class="form-control" placeholder="custom id">
        </li>
        <li style="display:none;">
            <label><?php echo $this->translate('Label Element Class'); ?></label>
            <input type="text" name="number_label_class" class="form-control" placeholder="class1 class2..">
        </li>
        <li style="display:none;">
            <label><?php echo $this->translate('Label Element Id'); ?></label>
            <input type="text" name="number_label_id" class="form-control"  placeholder="custom id">
        </li>
        <br />
		<li>
			<br><button class="btn btn-primary" id="add_form_checkbox"><?php echo $this->translate('Save'); ?></button>
		</li>
	</ul>
</form>

<?php echo '<code>'.$this->result->id.'</code>'; ?>