<?php $this->plugin('translate')->setTranslatorTextDomain('citroen');?>
<?php echo '<h3>'.$this->translate($this->result->name).'</h3>'; ?>

<form action="/form" method="post" name="add_form_data" id="add_form_data" class="<?php echo $this->result->id; ?>">
	<ul class="nav nav-list">
        <li>
            <label><?php echo $this->translate('Drop Down ID Name'); ?></label>
            <input type="text" name="input_name" class="form-control" maxlength="255" value="name">
        </li>
		<li>
			<label><?php echo $this->translate('Replace Name Text'); ?></label>
			<input type="text" name="text_label" class="form-control" maxlength="255" value="Drop Down">
		</li>
        <li>
            <fieldset class="choices">
                <p><?php echo $this->translate($this->result->name); ?> <?php echo $this->translate('Choices'); ?></p>
                <ul class="element_choices">
                    <?php for($i=0; $i<$this->result->length; $i++){ ?>
                    <li class="duplicate_input">
                        <input class="input-small form-control" type="text" value="Dropdown" name="rem<?php echo $i;?>">
                        <button class="btn btn-danger form-control" id="rem<?php echo $i;?>"><?php echo $this->translate('remove'); ?></button>
                        <button class="btn btn-info form-control" id="def<?php echo $i;?>"><?php echo $this->translate('set default'); ?></button>
                    </li>
                    <?php } ?>
                    <button class="btn btn-success form-control" id="add_new_dropdown_field"><?php echo $this->translate('add new field'); ?></button>
                </ul>
            </fieldset>
        </li><br>
        <li style="display:none;">
            <label><?php echo $this->translate('Validation Message'); ?></label>
            <input type="text" name="number_notinarray" class="form-control" maxlength="255" value="Please select your gender !">
        </li>
        <li style="display:none;">
            <label><?php echo $this->translate('Class'); ?></label>
            <input type="text" name="number_class" class="form-control" maxlength="255" placeholder="class1 class2..">
        </li>
        <li style="display:none;">
            <label><?php echo $this->translate('Id'); ?></label>
            <input type="text" name="number_id" class="form-control" maxlength="255" placeholder="custom id">
        </li>
		<li>
			<br><button class="btn btn-primary" id="add_form_dropdown"><?php echo $this->translate('Save'); ?></button>
		</li>
	</ul>
</form>

<?php echo '<code>'.$this->result->id.'</code>'; ?>