<?php $this->plugin('translate')->setTranslatorTextDomain('citroen');?>
<?php echo '<h3>'.$this->translate($this->result->name).'</h3>'; ?>

<form action="/form" method="post" name="add_form_data" id="add_form_data" class="<?php echo $this->result->id; ?>">
	<ul class="nav nav-list">
		<li>
			<label><?php echo $this->translate('Input ID Name'); ?></label>
			<input type="text" name="input_name"  class="form-control" maxlength="255" value="email">
		</li>
        <li>
			<label><?php echo $this->translate('Replace Name Text'); ?></label>
			<input type="text" name="text_label" class="form-control" maxlength="255" value="Email">
		</li>
		<li>
			<label><?php echo $this->translate('Placeholder Text'); ?></label>
			<input type="text" name="placeholder_text" class="form-control" maxlength="255" value="Email Address...">
		</li>
		<li style="display:none;">
			<label>Required</label>
			<select name="required" class="form-control" >
				<option value="no">No</option>
				<option value="yes">Yes</option>
			</select>
		</li>
        <li style="display:none;">
            <label>Validate between</label>
            <input type="number" name="number_min" class="form-control input-small" placeholder="min"><br />
            <input type="number" name="number_max" class="form-control input-small" placeholder="max">
            <p>number of characters.</p>
        </li>
        <li style="display:none;">
            <label>Invalid Email</label>
            <input type="text" name="invalid_type" class="form-control" maxlength="255" value="Email address format is not invalid">
        </li>
        <li style="display:none;"> 
            <label>Is Empty</label>
            <input type="text" name="is_empty_type" class="form-control" maxlength="255" value="Email address is required">
        </li>
        <li style="display:none;">
            <label>Class</label>
            <input type="text" name="number_class" class="form-control"  maxlength="255" placeholder="class1 class2..">
        </li>
        <li style="display:none;">
            <label>Id</label>
            <input type="text" name="number_id" class="form-control" maxlength="255" placeholder="custom id">
        </li>
        <br />
		<li>
			<button class="btn btn-primary" id="add_form_email"><?php echo $this->translate('Save'); ?></button>
		</li>
	</ul>
</form>

<?php echo '<code>'.$this->result->id.'</code>'; ?>