<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundcms');// Pour le texte ?>
<?php
$form = $this->loginForm;
$form->prepare();
?>

<div style="margin-top:200px;">
    <section class="col-xs-6 col-sm-4"></div>
    <section class="widget col-xs-6 col-sm-4"> 
        <header class="text-align-center">
            <h4>Playground CMS - Backoffice</h4>
        </header>
        <div class="body">
            <form class="no-margin" method="post" id="loginAdmin">
                <fieldset>
                    <div class="form-group no-margin">
                        <label for="email">Email</label>

                        <div class="input-group input-group-lg">
                                <span class="input-group-addon">
                                    <i class="fa fa-user"></i>
                                </span>
                            <input id="email" required type="text" class="form-control input-lg" name="identity" placeholder="<?php echo  $this->translate($form->get('identity')->getAttribute('placeholder')); ?>">
                        </div>

                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>

                        <div class="input-group input-group-lg">
                                <span class="input-group-addon">
                                    <i class="fa fa-lock"></i>
                                </span>
                            <input id="password" type="password" class="form-control input-lg" name="credential" placeholder="Your Password">
                        </div>
                    </div>
                </fieldset>
                <div class="form-actions">
                    <button type="submit" class="btn btn-block btn-lg btn-danger">
                        <span class="small-circle"><i class="fa fa-caret-right"></i></span>
                        <small>Sign In</small>
                    </button>
                    <div class="forgot"></div>
                </div>
            </form>
        </div>
    </section>

</div>