<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('admin'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active">Blocks</li>
            </ol>
        </section>
    </div>
</div>
<section class="widget">
    <header>
        <h4>
            <i class="fa fa-code"></i>
            Blocks list (<?php echo $this->nbBlock;?>)
        </h4>
    </header>
    <div class="pull-right margin-right30">
        <a href="<?php echo $this->url("admin/playgroundcmsadmin/page_create");?>">
            <button type="button" class="btn btn-success btn-lg" data-placement="top" data-original-title=".btn .btn-success .btn-lg">
                Add a block
            </button>
        </a>
    </div>
    <div class="clearfix"></div>
    <div class="divider"></div>
    <div class="body">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Type</th>
                    <th>Exportable</th>
                    <th>Gallery</th>
                    <th>Template</th>
                    <th>Created date</th>
                    <th class="td-actions">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->blocksPaginator as $block) : ?>
                    <tr>
                        <td>
                            <?php echo $block->getName(); ?>
                        </td>
                        <td>
                            <?php echo $block->getSlug(); ?>
                        </td>
                        <td>
                            <?php echo $block->getType(); ?>
                        </td>
                        <td>
                            <?php 
                            $isExportable = $block->getIsExportable(); 
                            if($isExportable) : 
                            ?>
                                <div class="feed-item">
                                    <div class="icon">
                                        <i class="fa fa-check color-green"></i>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div class="feed-item">
                                    <div class="icon">
                                        <i class="fa fa-times color-red"></i>
                                    </div>
                                </div>
                            <?php endif;  ?>
                        </td>
                        <td>
                        <?php 
                            $isGallery = $block->getIsGallery(); 
                            if($isExportable) : 
                            ?>
                                <div class="feed-item">
                                    <div class="icon">
                                        <i class="fa fa-check color-green"></i>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div class="feed-item">
                                    <div class="icon">
                                        <i class="fa fa-times color-red"></i>
                                    </div>
                                </div>
                            <?php endif;  ?>
                        </td>
                        <td>
                            <?php $templates = json_decode($block->getTemplateContext(), true); ?>
                            <?php foreach ($templates as $key => $value) : ?>
                                <?php echo $key." : ".$value."<br />"; ?>
                            <?php endforeach; ?>
                        </td>
                        <td><?php echo $block->getCreatedAt()->format('d/m/Y H:i:s'); ?></td>
                        <td class="td-actions">
                            <a href="<?php echo $this->url('admin/playgroundcmsadmin/page_edit', array('id' => $block->getId()));?>" class="btn btn-xs btn-success">
                                <i class="btn-icon-only fa fa-pencil"></i>                                       
                            </a>
                            <a href="javascript:;" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#myModal_<?php echo $block->getId(); ?>">
                                <i class="btn-icon-only fa fa-times"></i>                                       
                            </a>
                        </td>
                        <div id="myModal_<?php echo $block->getId(); ?>" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h4 class="modal-title" id="myModalLabel">Confirm the deletion of the block ?</h4>
                                    </div>
                                    <div class="modal-body">
                                        <h4><?php echo $block->getName(); ?></h4>
                                        <h5>Type :</h5>
                                        <p> <?php echo $block->getType(); ?>
                                        <h5>Templates :</h5>
                                        <p>
                                            <?php foreach ($templates as $key => $value) : ?>
                                                <?php echo $key." : ".$value."<br />"; ?>
                                            <?php endforeach; ?>
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        <a href="<?php echo $this->url('admin/playgroundcmsadmin/page_remove', array('id' => $block->getId()));?>">
                                            <button type="button" class="btn btn-danger">Remove</button>
                                        </a>
                                    </div>

                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div> 
    <?php $paginator =  $this->paginationControl($this->blocksPaginator , 'Sliding', 'playground-cms/partial/pagination.phtml', array('uri' => $this->url('admin/playgroundcmsadmin/block'), "countResults" => $this->nbBlock)); ?> 
    <?php if(strlen($paginator) > 10) :?>
            <div class="divider"></div>
            <?php echo $paginator; ?>
    <?php endif; ?>
    <div class="clearfix"></div>
    <div class="divider"></div>
    <div class="pull-right margin-right30">
        <a href="<?php echo $this->url("admin/playgroundcmsadmin/page_create");?>">
            <button type="button" class="btn btn-success btn-lg" data-placement="top" data-original-title=".btn .btn-success .btn-lg">
                Add a block
            </button>
        </a>
    </div>
    <div class="clearfix"></div>
</section>



