<?php echo $this->content; ?>


<script type="text/javascript">
    var informations = new Array();
    if ( ! document.createTreeWalker ) {
        throw( new Error( "Browser does not support createTreeWalker()." ) );
    }

    function filter(node) {
        return( NodeFilter.FILTER_ACCEPT );
    }
    filter.acceptNode = filter;
    var treeWalker = document.createTreeWalker(
        document.body,
        NodeFilter.SHOW_COMMENT,
        filter,
        false
    );

    while ( treeWalker.nextNode() ) {
        if (treeWalker.currentNode.nodeValue.substring(0, 2) != " /") {
            informations.push(treeWalker.currentNode.nodeValue);
        }
    }

    var html = '<div id="debug_pgcms"><ul class="list-group">';
    for (key in informations) {
        html += '<li class="list-group-item">'+informations[key]+'</li>';
    }
    html += '</ul></div>';
    //$("body").append(html);
    $("#debug_pgcms").hide();
</script>