<?php
// get child view
$children = $this->viewModel()->getCurrent()->getChildren();
$childView = $children[0];

echo $this->doctype();
?>

<html lang="<?php echo strtolower($childView->locale); ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('POC - Playground CMS')->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <!-- Le styles -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); ?>
        
    </head>
    <body>
       
            <?php echo $this->content; ?>
        
        

        
        <!-- Scripts -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <?php
        echo $this->headScript();
        echo $this->inlineScript();
        ?>

    </body> 
</html>