<?php
$children = $this->viewModel()
->getCurrent()
->getChildren();
if(isset($children[0])){
    $ourView  = $children[0];
}

?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle('Playground CMS - Admin')->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

<!-- Le styles -->
<?php /*echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))*/
?>

<!-- Scripts -->
<?php /*echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))*/

?>
<?php
	echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
?>
</head>
<body>
    <header class="navbar">
        
        <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <ul class="nav navbar-nav navbar-left">
                    <li><a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate('Home'); ?></a></li>
                    <?php echo $this->adminMenu()->setPartial(array('playground-core/menu.phtml', 'default')); ?>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <?php if(strpos($this->zfcUserIdentity()->getEmail(), "adfab.fr") !== false) : ?>
                        <?php endif; ?>
                        <li><a href="/" target="_blank"><?php echo $this->translate('Access to frontend'); ?> <span class="glyphicon glyphicon-chevron-right"></span></a></li>
                        <li><a href="<?php echo $this->url('frontend/zfcuser/logout', array('channel' => $this->channel)) ?>?redirect=<?php echo $this->url('admin', array('channel' => $this->channel)) ?>"
                                class="logout"><?php echo $this->translate('logout'); ?> <span class="glyphicon glyphicon-log-out"></span></a></li>
                        </ul>
                    </li>
                </ul>
    		</nav>
    	</div>
    </header>
	<div class="container">
		<?php echo $this->navigation()
		->breadcrumbs('admin_navigation')
		->setMaxDepth(3)
		->setPartial(array('playground-core/breadcrumbs.phtml', 'default'));
		?>
		<?php echo $this->content; ?>

		<footer>
			<p><?php echo $this->translate('copyright'); ?></p>
		</footer>
	</div>
	<!-- /container -->
	<?php echo $this->inlineScript() ?>
</body>
</html>


<script>
$(document).ready(function() {
    $($($('.nav')[0]).children()[1]).remove();
});
</script>