<?php
$children = $this->viewModel()
->getCurrent()
->getChildren();
if(isset($children[0])){
    $ourView  = $children[0];
}

?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
<?php 
    echo $this->headTitle('Playground CMS - Admin')->setSeparator(' - ')->setAutoEscape(false);
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
	echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
?>
</head>

<body>
	<div class="container">
    	<?php if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
    	<ul class="flashMessages">
    		<?php foreach ($ourView->flashMessages as $fMessage) : ?>
    		<li><?php echo $fMessage; ?></li>
    		<?php endforeach; ?>
    	</ul>
    	<?php endif; ?>

    <div class="row">
        <div class="col-md-offset-4 col-md-4 col-sm-offset-4 col-sm-4 col-lg-4 col-lg-offset-4">
            <div class="panel panel-default">
                
                <div class="panel-heading">
                    <h3 class="panel-title">Playground CMS - Back</h3>
                </div>
              
                <div class="panel-body">
                <?php echo $this->content; ?>
                </div>
            </div>
        </div>
    </div>

	</div>
	<!-- /container -->
	<?php echo $this->inlineScript() ?>
</body>
</html>
