<?php
$children = $this->viewModel()
->getCurrent()
->getChildren();
if(isset($children[0])){
    $ourView  = $children[0];
}

?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
<?php 
    echo $this->headTitle('Playground CMS - Admin')->setSeparator(' - ')->setAutoEscape(false);
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
?>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" />

</head>
<body>
    <div id="wrap">
        <nav class="navbar navbar-inverse" role="navigation">

            <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <i class="glyphicon glyphicon-cog"></i>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('admin'); ?>">Playground CMS</a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">        
                        <a href="javscript:;" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="glyphicon glyphicon-user"></i>
                            <?php echo $this->zfcUserIdentity()->getFirstname(); ?> <?php echo $this->zfcUserIdentity()->getLastname(); ?>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/" target="_blank"><?php echo $this->translate('Access to frontend'); ?></a></li>
                            <?php $urlLogout =  trim($this->url('frontend/zfcuser/logout', array('channel' => $this->channel))."?redirect=".$this->url('admin', array('channel' => $this->channel)),'/'); ?>
                            <li><a href="/<?php echo $urlLogout; ?>" class="logout"><?php echo $this->translate('Logout'); ?></a></li>
                            <li class="divider"></li>
                            <li><a href="#"><?php echo $this->translate('Help'); ?></a></li>
                        </ul>
                    </li>
                </ul>
              </div>
            </div>
        </nav>

        <div class="subnavbar">
            <div class="subnavbar-inner">
                <div class="container">
                    <a href="javascript:;" class="subnav-toggle" data-toggle="collapse" data-target=".subnav-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <i class="glyphicon glyphicon-list"></i>
                    </a>
                    <div class="collapse subnav-collapse">
                        <ul class="mainnav">
                        
                            <li class="<?php echo $this->nav=='dashboard'?'active':''?>">
                                <a href="<?php echo $this->url('admin'); ?>">
                                    <i class="glyphicon glyphicon-home"></i>
                                    <span>Dashboard</span>
                                </a>                        
                            </li>
                            
                            <li class="dropdown <?php echo $this->nav=='cms'?'active':''?>">                   
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="glyphicon glyphicon-cog"></i>
                                    <span>CMS</span>
                                    <b class="caret"></b>
                                </a>        
                            
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/page'); ?>">Bloc</a></li>
                                    <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/page'); ?>">Layout</a></li>
                                    <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/page'); ?>">Page</a></li>
                                    <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/page'); ?>">Template</a></li>
                                    <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/page'); ?>">Zone</a></li>
                                </ul>               
                            </li>
                            <li class="dropdown <?php echo $this->nav=='content'?'active':''?>">                   
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="glyphicon glyphicon-book"></i>
                                    <span>Contenus</span>
                                    <b class="caret"></b>
                                </a>        
                            
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/page'); ?>">Article</a></li>
                                    <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/page'); ?>">Menu</a></li>
                                    <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/page'); ?>">Sondage</a></li>
                                </ul>               
                            </li>
                        
                        </ul>
                    </div>

                </div>
            
            </div> 

        </div>
    	
   <?php echo $this->content; ?>
</div>
<div class=="clearfix">&nbsp;</div>
<div class="footer">
    <div class="container">
        <div class="row">
            <div id="footer-copyright" class="col-md-6">
               © Playground CMS 2014
            </div> <!-- /span6 -->
        </div> <!-- /row -->
    </div> <!-- /container -->
</div>
	<!-- /container -->
	<?php echo $this->inlineScript() ?>
</body>
</html>


<script>
$(document).ready(function() {
    $($($('.nav')[0]).children()[1]).remove();
});
</script>