<div class="row">
    <div class="col-md-12">
        <h2 class="page-title">Dashboard</h2>
    </div>
</div>
<div class="row">
    <div class="row">
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-desktop"></i>
                    </div>
                    <div class="description">
                        <strong>xx</strong> pages
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-bold"></i>
                    </div>
                    <div class="description">
                        <strong>xx</strong> Articles
                    </div>
                </div>
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-question"></i>
                    </div>
                    <div class="description">
                        <strong>xx</strong> polls
                    </div>
                </div>
            </div>
            
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-users"></i>
                    </div>
                    <div class="description">
                        <strong>xxx</strong> users
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-comments"></i>
                    </div>
                    <div class="description">
                        <strong>xx</strong> comments
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-code"></i>
                    </div>
                    <div class="description">
                        <strong>xx</strong> blocks
                    </div>
                </div>
            </div>
        </div>
            <div class="col-md-8">
                   <section class="widget large">
                    <header>
                        <h4>
                            <i class="fa fa-bold"></i>
                            Articles
                        </h4>
                        <div class="actions">
                            <button class="btn btn-transparent btn-xs">Show All <i class="fa fa-arrow-down"></i></button>
                        </div>
                    </header>
                    <div class="body">
                        <div class="" style="position: relative; overflow: hidden; width: auto; height: auto;"><div id="feed" class="feed" style="overflow: hidden; width: auto; height: auto;">
                            <div class="wrapper">
                                <div class="vertical-line"></div>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-times color-red"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            10 h
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-times color-red"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            14 h
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-times color-orange"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            Yesterday
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-times color-red"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            Yesterday
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-check color-green"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            8 days ago
                                        </div>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="widget large">
                    <header>
                        <h4>
                            <i class="fa fa-comments"></i>
                            Comments
                        </h4>
                    </header>
                    <div class="body">
                        <div id="chat" class="chat">
                            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: auto;"><div id="chat-messages" class="chat-messages" style="overflow: hidden; width: auto; height: auto;">
                                <div class="chat-message">
                                    <div class="sender pull-left">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            4 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            Hey Sam, how is it going? But I must explain to you how all this mistaken
                                            idea of denouncing of a pleasure and praising pain was born
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-message">
                                    <div class="sender pull-right">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            3 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body on-left">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            Pretty good. Doing my homework..  No one rejects, dislikes, or avoids
                                            pleasure itself, because it is pleasure, but because
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-message">
                                    <div class="sender pull-left">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            2 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            Any chance to go out? To take a trivial example, which of us ever undertakes
                                            laborious physical exercise, except to obtain some advantage
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-message">
                                    <div class="sender pull-right">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            2 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body on-left">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            .. Maybe 40-50 mins. I don't know exactly. On the other hand, we denounce
                                            with righteous indignation and dislike men who are so beguiled
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-message">
                                    <div class="sender pull-left">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            1 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            Anyway sounds great! These cases are perfectly simple and easy to
                                            distinguish.
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-md-4">
                <section class="widget large">
                    <header>
                        <h4>
                            <i class="eicon-share"></i>
                            Feed
                        </h4>
                        <div class="actions">
                            <button class="btn btn-transparent btn-xs">Show All <i class="fa fa-arrow-down"></i></button>
                        </div>
                    </header>
                    <div class="body">
                        <div class="" style="position: relative; overflow: hidden; width: auto; height: auto;"><div id="feed" class="feed" style="overflow: hidden; width: auto; height: auto;">
                            <div class="wrapper">
                                <div class="vertical-line"></div>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-comment"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">John Doe</a> commented on <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            3 h
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-bold color-red"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            New article <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a> by <a href="#">Thomas ROGER</a>.
                                        </div>
                                        <div class="time pull-left">
                                            10 h
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            New user <a href="#">Thomas ROGER</a> registered.
                                        </div>
                                        <div class="time pull-left">
                                            Today
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-desktop"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            New Page <a href="#">Home</a> by <a href="#">Thomas ROGER</a>.
                                        </div>
                                        <div class="time pull-left">
                                            Yesterday
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-arrow-down"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Load more...</a>
                                        </div>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="widget widget-tabs">
                    <header>
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#stats" data-toggle="tab">Users</a>
                            </li>
                            <li>
                                <a href="#report" data-toggle="tab">Pages</a>
                            </li>
                            <li>
                                <a href="#dropdown1" data-toggle="tab">Blocks</a>
                            </li>
                        </ul>
                    </header>
                    <div class="body tab-content">
                        <div id="stats" class="tab-pane active clearfix">
                            <h5 class="tab-header"><i class="fa fa-group"></i> Last logged-in users</h5>
                            <ul class="news-list">
                                <li>
                                    <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" alt="" class="pull-left img-circle">
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">Thomas ROGER</a></div>
                                        <div class="position">Software Engineer</div>
                                        <div class="time">Last logged-in: Mar 20, 18:46</div>
                                    </div>
                                </li>
                                <li>
                                    <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" alt="" class="pull-left img-circle">
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">Thomas ROGER</a></div>
                                        <div class="position">Software Engineer</div>
                                        <div class="time">Last logged-in: Mar 23, 9:02</div>
                                    </div>
                                </li>
                                <li>
                                    <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" alt="" class="pull-left img-circle">
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">Thomas ROGER</a></div>
                                        <div class="position">Software Engineer</div>
                                        <div class="time">Last logged-in: Jun 6, 15:34</div>
                                    </div>
                                </li>
                                <li>
                                    <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" alt="" class="pull-left img-circle">
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">Thomas ROGER</a></div>
                                        <div class="position">Software Engineer</div>
                                        <div class="time">Last logged-in: Jun 8, 17:20</div>
                                    </div>
                                </li>
                                <li>
                                    <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>g" alt="" class="pull-left img-circle">
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">Thomas ROGER</a></div>
                                        <div class="position">Software Engineer</div>
                                        <div class="time">Last logged-in: Jun 8, 9:13</div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div id="report" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-desktop"></i> Last pages</h5>
                            <ul class="news-list news-list-no-hover">
                                <li>
                                    <section class="feed-item">
                                        <div class="icon pull-left">
                                            <i class="fa fa-check color-green"></i>
                                        </div>
                                        <div class="feed-item-body">
                                            <div class="text">
                                                <a href="#">Home</a>.
                                            </div>
                                            <div class="time pull-left">
                                                Yesterday
                                            </div>
                                        </div>
                                    </section>
                                </li>
                                <li>
                                    <section class="feed-item">
                                        <div class="icon pull-left">
                                            <i class="fa fa-times color-red"></i>
                                        </div>
                                        <div class="feed-item-body">
                                            <div class="text">
                                                <a href="#">Sommaire</a>.
                                            </div>
                                            <div class="time pull-left">
                                                8 days ago
                                            </div>
                                        </div>
                                    </section>
                                </li>
                            </ul>
                        </div>
                        <div id="dropdown1" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-code"></i> Last Block</h5>
                            <ul class="news-list">
                                <li>
                                    <div class="icon pull-left">
                                        <i class="fa fa-code color-green"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">List block with Filter, Sort and Pager (Name like '%HTML%') (Name DESC) (2 blocks per page, limit result to 5 blocks)</a></div>
                                        <div class="comment">
                                            PlaygroundCMS\Blocks\BlockListController
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon pull-left">
                                        <i class="fa fa-code color-green"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">List block with Sort (Name DESC)</a></div>
                                        <div class="comment">
                                            PlaygroundCMS\Blocks\BlockListController
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon pull-left">
                                        <i class="fa fa-code color-green"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">List block with Filters (Name like '%HTML%')</a></div>
                                        <div class="comment">
                                            PlaygroundCMS\Blocks\BlockListController
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon pull-left">
                                        <i class="fa fa-code color-green"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">List block</a></div>
                                        <div class="comment">
                                           PlaygroundCMS\Blocks\BlockListController
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon pull-left">
                                        <i class="fa fa-code color-green"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="#">HTML Content 2</a></div>
                                        <div class="comment">
                                            PlaygroundCMS\Blocks\FreeHTMLController
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>
            </div>
        </div>