<div class="row">
    <div class="col-md-12">
        <h2 class="page-title">Dashboard</h2>
    </div>
</div>
<div class="row">
    <div class="row">
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="<?php echo $this->url('admin/playgroundcmsadmin/page'); ?>" class="color-white">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-desktop"></i>
                    </div>
                    <div class="description">
                        <strong><?php echo count($this->pages); ?></strong> pages
                    </div>
                </div>
                </a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-bold"></i>
                    </div>
                    <div class="description">
                        <strong>xx</strong> Articles
                    </div>
                </div>
            </div>

            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-question"></i>
                    </div>
                    <div class="description">
                        <strong>xx</strong> polls
                    </div>
                </div>
            </div>
            
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-users"></i>
                    </div>
                    <div class="description">
                        <strong><?php echo count($this->users); ?></strong> users
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-comments"></i>
                    </div>
                    <div class="description">
                        <strong>xx</strong> comments
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <div class="box">
                    <div class="icon">
                        <i class="fa fa-code"></i>
                    </div>
                    <div class="description">
                        <strong><?php echo count($this->blocks); ?></strong> blocks
                    </div>
                </div>
            </div>
        </div>
            <div class="col-md-8">
                <section class="widget widget-tabs large">
                    <header>
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#stats" data-toggle="tab">Users (<?php echo count($this->users); ?>)</a>
                            </li>
                            <li>
                                <a href="#report" data-toggle="tab">Pages (<?php echo count($this->pages); ?>)</a>
                            </li>
                            <li>
                                <a href="#dropdown1" data-toggle="tab">Blocks  (<?php echo count($this->blocks); ?>)</a>
                            </li>
                        </ul>
                    </header>
                    <div class="body tab-content">
                        <div id="stats" class="tab-pane active clearfix">
                            <h5 class="tab-header"><i class="fa fa-group"></i> Last created users </h5>
                            <?php $users = array_reverse(array_slice($this->users, -10, 10)); ?>
                            <ul class="news-list">
                                <?php foreach ($users as $user) : ?>
                                    <li>
                                        <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($user->getEmail())));?>" alt="" class="pull-left img-circle">
                                        <div class="news-item-info">
                                            <div class="name"><a href="#"><?php echo ucfirst($user->getFirstname()); ?> <?php echo strtoupper($user->getLastname()); ?></a></div>
                                            <div class="position"><?php echo $user->getEmail(); ?></div>
                                            <div class="time">Created at <?php echo $user->getCreatedAt()->format('d M Y, H:i'); ?></div>
                                        </div>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div id="report" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-desktop"></i> Last pages</h5>
                            <?php $pages = array_reverse(array_slice($this->pages, -10, 10)); ?>
                            <ul class="news-list">
                                <?php foreach ($pages as $page) : ?>
                                    <li>
                                        <section class="feed-item">
                                            <div class="icon pull-left">
                                                <?php $color = "red";  ?>
                                                <?php if($page->checkVisibility()) $color="green"; ?>
                                                <i class="fa fa-check color-<?php echo $color; ?>"></i>
                                            </div>
                                            <div class="feed-item-body">
                                                <div class="text">
                                                    <a href="#"><?php echo $page->getTitle(); ?></a>.
                                                </div>
                                                <div class="time pull-left">
                                                    Created at <?php echo $page->getCreatedAt()->format('d M Y, H:i'); ?>
                                                </div>
                                            </div>
                                        </section>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div id="dropdown1" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-code"></i> Last Block</h5>
                            <?php $blocks = array_reverse(array_slice($this->blocks, -10, 10)); ?>
                            <ul class="news-list">
                                <?php foreach ($blocks as $block) : ?>
                                <li>
                                    <div class="icon pull-left">
                                        <i class="fa fa-code"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="#"><?php echo $block->getName(); ?></a></div>
                                        <div class="comment">
                                            <?php echo $block->getType(); ?>
                                        </div>
                                        <div class="time pull-left">
                                            Created at <?php echo $block->getCreatedAt()->format('d M Y, H:i'); ?>
                                        </div>
                                    </div>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </section>
                <section class="widget large">
                    <header>
                        <h4>
                            <i class="fa fa-comments"></i>
                            Comments
                        </h4>
                    </header>
                    <div class="body">
                        <div id="chat" class="chat">
                            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: auto;"><div id="chat-messages" class="chat-messages" style="overflow: hidden; width: auto; height: auto;">
                                <div class="chat-message">
                                    <div class="sender pull-left">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            4 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            Hey Sam, how is it going? But I must explain to you how all this mistaken
                                            idea of denouncing of a pleasure and praising pain was born
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-message">
                                    <div class="sender pull-right">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            3 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body on-left">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            Pretty good. Doing my homework..  No one rejects, dislikes, or avoids
                                            pleasure itself, because it is pleasure, but because
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-message">
                                    <div class="sender pull-left">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            2 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            Any chance to go out? To take a trivial example, which of us ever undertakes
                                            laborious physical exercise, except to obtain some advantage
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-message">
                                    <div class="sender pull-right">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            2 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body on-left">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            .. Maybe 40-50 mins. I don't know exactly. On the other hand, we denounce
                                            with righteous indignation and dislike men who are so beguiled
                                        </div>
                                    </div>
                                </div>
                                <div class="chat-message">
                                    <div class="sender pull-left">
                                        <div class="icon">
                                            <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($this->zfcUserIdentity()->getEmail())));?>" class="img-circle" alt="">
                                        </div>
                                        <div class="time">
                                            1 min
                                        </div>
                                    </div>
                                    <div class="chat-message-body">
                                        <span class="arrow"></span>
                                        <div class="sender"><a href="#">Thomas ROGER</a></div>
                                        <div class="text">
                                            Anyway sounds great! These cases are perfectly simple and easy to
                                            distinguish.
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-md-4">
                <section class="widget large">
                    <header>
                        <h4>
                            <i class="fa fa-share"></i>
                            Feeds (<?php echo count($this->feeds); ?>)
                        </h4>
                        <div class="actions">
                            <button class="btn btn-transparent btn-xs">Show All <i class="fa fa-arrow-down"></i></button>
                        </div>
                    </header>
                    <div class="body">
                        <div class="" style="position: relative; overflow: hidden; width: auto; height: auto;"><div id="feed" class="feed" style="overflow: hidden; width: auto; height: auto;">
                            <div class="wrapper">
                                <div class="vertical-line"></div>
                                <?php $feeds = array_slice($this->feeds, 0, 10); ?>
                                <?php foreach ($feeds as $feed) : ?>
                                    <?php if (get_class($feed) == 'PlaygroundUser\Entity\User') : ?>
                                        <?php $type = 'user'; ?>
                                        <?php $message = 'New user <a href="#">'.ucfirst($feed->getFirstname()).' '.strtoupper($feed->getLastname()).'</a>.'; ?>
                                    <?php endif; ?>
                                    <?php if (get_class($feed) == 'PlaygroundCMS\Entity\Page') : ?>
                                        <?php $type = 'desktop'; ?>
                                        <?php $message = 'New page <a href="#">'.$feed->getTitle().'</a>.'; ?>
                                    <?php endif; ?>
                                    <?php if (get_class($feed) == 'PlaygroundCMS\Entity\Block') : ?>
                                        <?php $type = 'code'; ?>
                                        <?php $message = 'New block <a href="#">'.$feed->getName().'</a>.'; ?>
                                    <?php endif; ?>
                                    <section class="feed-item">
                                        <div class="icon pull-left">
                                            <i class="fa fa-<?php echo $type; ?>"></i>
                                        </div>
                                        <div class="feed-item-body">
                                            <div class="text">
                                                <?php echo $message; ?>
                                            </div>
                                            <div class="time pull-left">
                                                Created at <?php echo $feed->getCreatedAt()->format('d M Y, H:i'); ?>
                                            </div>
                                        </div>
                                    </section>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="widget large">
                    <header>
                        <h4>
                            <i class="fa fa-bold"></i>
                            Articles
                        </h4>
                        <div class="actions">
                            <button class="btn btn-transparent btn-xs">Show All <i class="fa fa-arrow-down"></i></button>
                        </div>
                    </header>
                    <div class="body">
                        <div class="" style="position: relative; overflow: hidden; width: auto; height: auto;"><div id="feed" class="feed" style="overflow: hidden; width: auto; height: auto;">
                            <div class="wrapper">
                                <div class="vertical-line"></div>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-times color-red"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            10 h
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-times color-red"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            14 h
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-times color-orange"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            Yesterday
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-times color-red"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            Yesterday
                                        </div>
                                    </div>
                                </section>
                                <section class="feed-item">
                                    <div class="icon pull-left">
                                        <i class="fa fa-check color-green"></i>
                                    </div>
                                    <div class="feed-item-body">
                                        <div class="text">
                                            <a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>.
                                        </div>
                                        <div class="time pull-left">
                                            8 days ago
                                        </div>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>