<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('admin'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active">Menus (<?php echo count($menus); ?>)</li>
            </ol>
        </section>
    </div>
</div>

<section class="widget large">
    <div class="body">
        <div class="" style="position: relative; overflow: hidden; width: auto; height: auto;">
            <div id="feed" class="feed" style="overflow: hidden; width: auto; height: auto;">
            <div class="wrapper">
                <div class="vertical-line"></div>
                
            </div>
        </div>
    </div>
</section>