
<section class="widget">
    <header>
        <h4>
            <i class="fa fa-desktop"></i>
            Listes des pages (<?php echo $this->nbPage;?>)
        </h4>
    </header>
    <div class="pull-right margin-right30">
        <button type="button" class="btn btn-success btn-lg" data-placement="top" data-original-title=".btn .btn-success .btn-lg">
            Add a page
        </button>
    </div>
    <div class="body">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Status</th>
                    <th>State</th>
                    <th>Start date of publication</th>
                    <th>End Date of publication</th>
                    <th>Urls</th>
                    <th>Layout</th>
                    <th>Created date</th>
                    <th class="td-actions">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->pagesPaginator as $page) : ?>
                    <tr>
                        <td><?php echo $page->getTitle(); ?></td>
                        <td>
                            <?php 
                                $visible = $page->checkVisibility(); 
                            ?>
                            <?php 
                            if($visible) : ?>
                                <div class="feed-item">
                                    <div class="icon">
                                        <i class="fa fa-check color-green"></i>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div class="feed-item">
                                    <div class="icon">
                                        <i class="fa fa-times color-red"></i>
                                    </div>
                                </div>
                            <?php endif;  ?>
                        </td>
                        <td>
                            <?php $labelType = "info" ?>
                            <?php if($page->getStatus() == 1 ) $labelType = "success"; ?>
                            <?php if($page->getStatus() == 2 ) $labelType = "warning"; ?>
                            <?php if($page->getStatus() == 3 ) $labelType = "important"; ?>
                            <span class="label label-<?php echo $labelType; ?>"><?php echo $page->getStatusName(); ?></span>
                            
                        </td>
                        <td><?php echo $page->getStartDate()->format('d/m/Y H:i:s'); ?></td>
                        <td><?php echo $page->getEndDate()->format('d/m/Y H:i:s'); ?></td>
                        <td>
                            <?php $ressources = $this->ressourcesCollection[$page->getId()]; ?>
                            <?php foreach ($ressources as $key => $ressource) : ?>
                                <?php echo $ressource->getUrl()."<br />"; ?>
                            <?php endforeach; ?>
                        </td>
                        <td>
                            <?php $layouts = json_decode($ressources['fr_FR']->getLayoutContext(), true); ?>
                            <?php foreach ($layouts as $key => $value) : ?>
                                <?php echo $key." : ".$value."<br />"; ?>
                            <?php endforeach; ?>
                        </td>
                        <td><?php echo $page->getCreatedAt()->format('d/m/Y H:i:s'); ?></td>
                        <td class="td-actions">
                            <a href="javascript:;" class="btn btn-xs btn-danger">
                                <i class="btn-icon-only fa fa-times"></i>                                       
                            </a>
                             <a href="javascript:;" class="btn btn-xs btn-success">
                                <i class="btn-icon-only fa fa-pencil"></i>                                       
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div> 
    <?php echo $this->paginationControl($this->pagesPaginator , 'Sliding', 'playground-cms/partial/pagination.phtml', array('uri' => $this->url('admin/playgroundcmsadmin/page'), "countResults" => $this->nbPage)); ?> 
</section>



