<div class="widget stacked widget-table action-table">
                    
    <div class="widget-header">
        <i class="glyphicon glyphicon-th-list"></i>
        <h3>Listes des pages (<?php echo $this->nbPage;?>)</h3>
    </div>
    
    <div class="widget-content">
        
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Status</th>
                    <th>Date of publishing</th>
                    <th>Date of end of publishing</th>
                    <th>Urls</th>
                    <th>Layout</th>
                    <th>Created date</th>
                    <th class="td-actions">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Actions&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->pagesPaginator as $page) : ?>
                    <tr>
                        <td><?php echo $page->getTitle(); ?></td>
                        <td>
                            <?php 
                                $visible = $page->checkVisibility(); 
                            ?>
                            <?php 
                            if($visible) : ?>
                                <span class="label label-success">Visible</span>
                            <?php else: ?>
                                <span class="label label-danger">Non Visible</span>
                            <?php endif;  ?>
                        </td>
                        <td><?php echo $page->getStartDate()->format('d/m/Y H:i:s'); ?></td>
                        <td><?php echo $page->getEndDate()->format('d/m/Y H:i:s'); ?></td>
                        <td>
                            <?php $ressources = $this->ressourcesCollection[$page->getId()]; ?>
                            <?php foreach ($ressources as $key => $ressource) : ?>
                                <?php echo $ressource->getUrl()."<br />"; ?>
                            <?php endforeach; ?>
                        </td>
                        <td>
                            <?php $layouts = json_decode($ressources['fr_FR']->getLayoutContext(), true); ?>
                            <?php foreach ($layouts as $key => $value) : ?>
                                <?php echo $key." : ".$value."<br />"; ?>
                            <?php endforeach; ?>
                        </td>
                        <td><?php echo $page->getCreatedAt()->format('d/m/Y H:i:s'); ?></td>
                        <td class="td-actions">
                            <a href="javascript:;" class="btn btn-xs btn-danger">
                                <i class="btn-icon-only glyphicon glyphicon-remove"></i>                                       
                            </a>
                             <a href="javascript:;" class="btn btn-xs btn-success">
                                <i class="btn-icon-only glyphicon glyphicon-pencil"></i>                                       
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
    </div>
</div>

<?php echo $this->paginationControl($this->pagesPaginator , 'Sliding', 'playground-cms/partial/pagination.phtml', array('uri' => $this->url('admin/playgroundcmsadmin/page'), "countResults" => $this->nbPage)); ?>
