<?php if ($this->pageCount && ($this->pageCount > 1)): ?>
<div class="text-center">
    <ul class="pagination">
        <!-- First page link -->
        <li<?php echo (isset($this->first)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $uri.'?page='.$this->first?>">&lt;&lt; <?php echo $this->cmsTranslate('First'); ?></a>
        </li>

        <!-- Previous page link -->
        <li<?php echo (isset($this->previous)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $uri.'?page='.$this->previous?>">&lt; <?php echo ('Previous'); ?></a>
        </li>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
        <li<?php echo ($page == $this->current) ? ' class="active"' : ''; ?>>
            <a href="<?php echo $uri.'?page='.$page?>"><?php echo $page; ?></a>
        </li>
        <?php endforeach; ?>

        <!-- Next page link -->
        <li<?php echo (isset($this->next)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $uri.'?page='.$this->next?>"><?php echo ('Next'); ?> &gt;</a>
        </li>

        <!-- Last page link -->
        <li<?php echo (isset($this->last)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo $uri.'?page='.$this->last?>"><?php echo ('Last'); ?> &gt;&gt;</a>
        </li>
    </ul>
    <ul class="pager">
        <li class="disabled"><a href="#"><?php echo ('Number of results : ').$countResults ?> - <?php echo ('Number of pages : ').$this->pageCount ?></a></li>
    </ul>
</div>
<?php endif; ?>

<?php
$script = $this->inlineScript();
$script->appendScript(<<<'EOT'
    
$(".pagination .disabled a").click(function() {
  return false;
});

$(".pager .disabled a").click(function() {
  return false;
});

EOT
);