<?php $return = $this->return; ?>
<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('admin'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a href="<?php echo $this->url('admin/playgroundpublishingadmin/categories'); ?>"><i class="fa fa-desktop"></i> Categories</a></li>
                <li class="active">Create a new category</li>
            </ol>
        </section>
        <h2 class="page-title"><i class="fa fa-book"></i> Create a new category</h2>
    </div>
</div>
<form method="POST">
<?php if(!empty($return) && $return['status'] != 0) : ?>
    <div class="row">
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="fa fa-ban"></i> <strong><?php echo $return['message'];?>!</strong></h4>
        </div>
    </div>
<?php endif; ?>
<div class="row">
    <div class="col-md-8">
        <section class="widget">
            <header>
                <h4>Content informations</h4>
            </header>
            <div class="body">
                <section class="widget widget-tabs large">
                    <header>
                        <ul class="nav nav-tabs">
                            <?php $cpt = 0; ?>
                            <?php foreach ($this->locales as $locale) : ?>
                                <li class="<?php echo $cpt==0?'active':'';?>">
                                    <?php $locales = explode('_', $locale->getLocale()); ?>
                                    <a href="#<?php echo $locale->getLocale(); ?>" data-toggle="tab"> <img src="blank.gif" class="flag flag-<?php echo strtolower($locales[1]);?>" alt="<?php echo $locale->getLocale(); ?>" /> <?php echo $locale->getName(); ?></a>
                                </li>
                                <?php $cpt ++; ?>
                            <?php endforeach; ?>
                        </ul>
                    </header>
                    <div class="body tab-content">
                        <?php $cpt = 0; ?>
                        <?php foreach ($this->locales as $locale) : ?>
                            <?php $locales = explode('_', $locale->getLocale()); ?>
                            <div id="<?php echo $locale->getLocale(); ?>" class="tab-pane clearfix <?php echo $cpt==0?'active':'';?>">
                                <fieldset>
                                    <legend class="section"><img src="blank.gif" class="flag flag-<?php echo strtolower($locales[1]);?>" alt="<?php echo $locale->getLocale(); ?>" /> <?php echo $locale->getName(); ?></legend>
                                    <div class="form-horizontal" method="post" novalidate="novalidate" data-validate="parsley">
                                         <div class="control-group">
                                            <label for="description" class="control-label">Title <span class="required">*</span></label>
                                            <div class="controls form-group">
                                                <input type="text" id="first-name" name="category[<?php echo $locale->getLocale(); ?>][title]" class="form-control" value="<?php echo @$this->data['category'][$locale->getLocale()]['title'];?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label for="description" class="control-label">Description</label>
                                            <div class="controls form-group">
                                                <textarea id="description" rows="2" name="category[<?php echo $locale->getLocale(); ?>][description]" class="form-control"><?php echo @$this->data['category'][$locale->getLocale()]['description_seo'];?></textarea>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label for="description" class="control-label">Slug</label>
                                            <div class="controls form-group">
                                                <input type="text" id="first-name" name="category[<?php echo $locale->getLocale(); ?>][slug]" class="form-control" disabled>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                            <?php $cpt ++; ?>
                        <?php endforeach; ?> 
                    </div>
                </section>
            </div>
        </section>
    </div>
    <div class="col-md-4">
        <section class="widget">
            <header>
                <h4><i class="fa fa-cog"></i> Options</h4>
            </header>
            <div class="body">
                <div id="page-options" class="form-horizontal form-condensed label-left">
                    <fieldset>
                        <legend class="section"><i class="fa fa-calendar"></i> Publishing</legend>
                        <div class="control-group">
                            <label for="article-status" class="control-label">Status <span class="required">*</span></label>
                            <div class="controls form-group">
                                <select class="selectpicker show-tick" name="category[status]" data-live-search="true" data-size="5" data-width="100%">
                                    <option value="-1" data-content="" selected>Choose the status</option>
                                    <?php foreach ($categoryStatuses as $key => $value) : ?>
                                    <?php $labelType = "important" ?>
                                    <?php if($key == 1 ) $labelType = "success"; ?>
                                        <option value="<?php echo $key; ?>" data-content="<span class='label label-<?php echo $labelType; ?>'><?php echo $value; ?></span>" <?php echo @$this->data['page']["status"]===$key?'selected':'';?>><?php echo $value; ?></option>
                                    <?php endforeach; ?>
                              </select>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </section>
        <section class="widget">
            <header>
                <h4><i class="fa fa-plus"></i> Actions</h4>
            </header>
            <div class="body">
                <button type="submit" class="btn btn-success pull-right">Submit</button>
                <div class="clearfix">&nbsp;</div>
            </div>
        </section>
    </div>
</div>
</form>