<?php $return = $this->return; ?>
<?php $layout = $this->layout; ?>
<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('admin'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/layout'); ?>"><i class="fa fa-windows"></i> Layouts</a></li>
                <li class="active">Edit blocks for the layout : <?php echo $layout->getName(); ?></li>
            </ol>
        </section>
        <h2 class="page-title"><i class="fa fa-windows"></i> Edit blocks for the layout : <?php echo $layout->getName(); ?></h2>
    </div>
</div>
<form method="POST" ENCTYPE="multipart/form-data">
    <input type="text" id="layoutId" name="layout[id]" class="form-control hide" value="<?php echo $layout->getId()?>" >
<?php if(!empty($return) && $return['status'] != 0) : ?>
    <div class="row">
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="fa fa-ban"></i> <strong><?php echo $return['message'];?>!</strong></h4>
        </div>
    </div>
<?php endif; ?>
<div class="row layout">

</div>
</form>